### ISSUE TITLE
Errors occur due to incorrect config.

### ISSUE THREAD

**Issue by daniilberkutdev** [akumanomi1988/TapMonster_AutoBot#1]
File: `main.py`
In the latest version of the script, an error occurs in this line when correctly installing and setting the actual token:
`use_tapmonster = config[‘tapmonster’]`. 

Error is: `An unexpected error occurred: 'tapmonster'`.

I can assume that it occurs because there is no tapmonster property in config. Most likely **you just forgot to commit a new config**, because this line `tapmonster_api = TapMonster(config[‘tapmonster_query_id’])` also reads a non-existent property.

**Comment by akumanomi1988** [comment]
> File: `main.py`
> In the latest version of the script, an error occurs in this line when correctly installing and setting the actual token:
> `use_tapmonster = config[‘tapmonster’]`. 
> 
> Error is: `An unexpected error occurred: 'tapmonster'`.
> 
> I can assume that it occurs because there is no tapmonster property in config. Most likely **you just forgot to commit a new config**, because this line `tapmonster_api = TapMonster(config[‘tapmonster_query_id’])` also reads a non-existent property.

Thank you, you're absolutely right! I made a change to regenerate the token automatically so I wouldn’t have to renew it manually, and it worked for a few days, but they must have changed something because it stopped working. I had to revert to the previous method. Please try using the earlier version until I can fix it. Thanks! Also, if you join my clan, I’d really appreciate it.

https://t.me/tapmonsters_bot/start?startapp=ref1956860053-clanAKCJ7&startApp=ref1956860053-clanAKCJ7

**Comment by akumanomi1988** [comment]
> File: `main.py` In the latest version of the script, an error occurs in this line when correctly installing and setting the actual token: `use_tapmonster = config[‘tapmonster’]`.
> 
> Error is: `An unexpected error occurred: 'tapmonster'`.
> 
> I can assume that it occurs because there is no tapmonster property in config. Most likely **you just forgot to commit a new config**, because this line `tapmonster_api = TapMonster(config[‘tapmonster_query_id’])` also reads a non-existent property.

Hey! I checked the code, and in the configuration file, you’ll need to change tapmonster_token to tapmonster_query_id. You’ll also see this update in the config.example.json file.

Thanks a lot, and have a great day!

To locate the query_id, head to the developer menu, find the login function, and look under the "Payload" section as shown in the image.
![image](https://github.com/user-attachments/assets/3bd9895e-8010-4e27-948b-d22b66cbf688)
